@startuml
'https://plantuml.com/sequence-diagram

actor "Пользователь" as user
participant "сервис Order" as orderService
participant "сервис Catalog" as catalogService
participant "сервис Account" as accountService
participant "сервис User" as userService

group Покупка товара пользователем
    user -> orderService: Запрос на покупку
    activate user
    activate orderService
    orderService -> orderService: Транзакция
    orderService -> catalogService: Получение информации\nо товаре с транзакцией
    activate catalogService
    catalogService -> catalogService: Транзакция
    orderService <-- catalogService: Товар
    deactivate catalogService
    orderService -> orderService: Проверка на\nколичество товара
    group Нехватка товара
        orderService -> catalogService: Роллбек транзакции
        activate catalogService
        orderService <-- catalogService: Успех
        deactivate catalogService
        orderService -> orderService: Роллбек транзакции
        user <-- orderService: Ошибка\nнехватки товаров
    end group
    orderService -> accountService: Получение информации\nоб аккаунте с транзакцией
    activate accountService
    accountService -> accountService: Транзакция
    orderService <-- accountService: Аккаунт
    deactivate accountService
    orderService -> orderService: Проверка на нехватку средств
    group Нехватка средств
        orderService -> catalogService: Роллбек транзакции
        activate catalogService
        orderService <-- catalogService: Успех
        deactivate catalogService
        orderService -> accountService: Роллбек транзакции
        activate accountService
        orderService <-- accountService: Успех
        deactivate accountService
        orderService -> orderService: Роллбек транзакции
        user <-- orderService: Ошибка\nнехватки средств
    end group
    orderService -> orderService: Создание заказа
    orderService -> accountService: Вычитание средств
    activate accountService
    orderService <-- accountService: Аккаунт
    deactivate accountService
    orderService -> orderService: Коммит транзакции
    orderService -> catalogService: Коммит транзакции
    activate catalogService
    orderService <-- catalogService: Успех
    deactivate catalogService
    orderService -> accountService: Коммит транзакции
    activate accountService
    orderService <-- accountService: Успех
    deactivate accountService
    user <-- orderService: Заказ
end group

note over orderService
При возникновении ошибки, связанной с сетью (отсутствие сети),
либо 500 следует повторять запрос n раз с интервалом в м,
если запрос не отработает корректно - следует сделать роллбек
всех транзакций и отправить ошибку пользователю.
При возникновении ошибки, связанной с сущностями или бизнес
логикой (отсутствие товара с указанным id), следует сделать
роллбек всех транзакций и отправить ошибку пользователю.
end note

@enduml