@startuml
'https://plantuml.com/sequence-diagram

actor "Пользователь" as user
box mconst.rpg.catalog
    participant "Контроллер продуктов" as productController
    participant "Сервис продуктов" as productService
    participant "Репозиторий продуктов" as productRepository
end box
participant "База данных" as db

group Приёмка товаров на склад, кейс: существующий товар
    user -> productController: POST /products/:id/add-count\nКоличество добавляемого товара
    activate user
    activate productController
    productController -> productController: Валидация данных
    group Ошибка валидации
        productController --> user: Ошибка валидации
    end group
    productController -> productService: Добавить количество товаров
    activate productService
    productService -> productRepository: Добавить количество товаров
    activate productRepository
    productRepository -> db: Добавить количество товаров
    activate db
    db --> productRepository: Информация о товаре
    deactivate db
    productRepository --> productService: Информация о товаре
    deactivate productRepository
    productService --> productController: Информация о товаре
    deactivate productService
    productController --> user: Информация о товаре
    deactivate productController
    deactivate user
 end group

 group Приёмка товаров на склад, кейс: новый товар
    user -> productController: POST /products\nИнформация о товаре
    activate user
    activate productController
    productController -> productController: Валидация данных
    group Ошибка валидации
        productController --> user: Ошибка валидации
    end group
    productController -> productService: Добавить товар
    activate productService
    productService -> productRepository: Добавить товар
    activate productRepository
    productRepository -> db: Добавить товар
    activate db
    db --> productRepository: Информация о товаре
    deactivate db
    productRepository --> productService: Информация о товаре
    deactivate productRepository
    productService --> productController: Информация о товаре
    deactivate productService
    productController --> user: Информация о товаре
    deactivate productController
    deactivate user
end group

@enduml